name: Run unit tests

on:
  pull_request:

  # Allows manual run from the Actions tab
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: [ '3.10' ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install packages
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install -r tests/requirements-test.txt --index-url=https://packages.idmod.org/api/pypi/pypi-production/simple
      - name: Run unit-tests
        run: pytest -m unit -v
