name: tests

on:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - name: Install packages
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install -r tests/requirements-test.txt
          pip install -r tests/requirements-tools.txt
      - name: Run unit-tests
        run: pytest -m unit
